hortonworks-spark/spark-atlas-connector

.gitignore
Add metastore_db to gitignore.
=> Add metastore_db to gitignore.

pom.xml, src/main/scala/com/hortonworks/spark/atlas/RestAtlasClient.scala, src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala
Changes:
This is a initial PR to support Hive tables.
Test:
Manually tested in HDP cluster
=> [SQL] Support hive tables

src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala
Changes:
1. Create a thread to analyze queries. 
2. Refactor code: split the logic of query analyzation into small functions.
Testing:
Manually tested in HDP cluster.
=> [SQL] Create a thread to analyze queries and interact with Atlas

pom.xml
=> Use 2.3.1-SNAPSHOT to test with upcomming Apache Spark 2.3 RC3

pom.xml
=> [SAC-30] Use Apache Spark 2.3.0

spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala
Update KafkaHarvester get output topic method
=> [SAC-40] kafka output topic fail to get

pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClientConf.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/KafkaAtlasClient.scala
Atlas update its API based on https://issues.apache.org/jira/browse/ATLAS-2251. 
We need to update Spark Atlas as well. 
Pass Travis CI.
=> [SAC-48] Update for Atlas 1.0 update

pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasStreamingQueryEventTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkStreamingQueryEventProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/AtlasExternalEntityUtilsSuite.scala
This PR record the input and output place for Spark Streaming Query processing
Attached the output later.
=> [SAC-53]Track the sink information for Spark streaming query process #53

pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/KafkaAtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/utils/SparkUtils.scala
Update the API change for Atlas 1.1 
Local build and test
=> Update for Apache Atlas 1.1

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala
Currently, SAC is collecting some information at PreEvents like DropDatabasePreEvent. However, the database described in DropDatabasePreEvent might not exist and the main event DropDatabaseEvent will not arrive because it will fail. This PR fixes some PreEvent logic and handles explicitly as No-OPs for the others.
```scala
scala> sql("drop database sparkdb2")
2018-11-12 14:16:29 WARN  SparkCatalogEventProcessor:48 - Caught exception during parsing event
org.apache.spark.sql.catalyst.analysis.NoSuchDatabaseException: Database 'sparkdb2' not found;
...
at com.hortonworks.spark.atlas.AbstractEventProcessor$$anon$1.run(AbstractEventProcessor.scala:39)
```
Manual with Apache Atlas 1.1.0 and Apache Spark 2.4.0
=> [SAC-91] Spark Catalog PreEvent should be handled correctly

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessorSuite.scala
Currently, if SAC fails to collect information at `PreDrop` events, it fails to `Drop` events. At least, it should succeed to remove db/table entities. For the related sub-entities, Atlas or SAC will handle later. For now, it's a best-effort approach.
```scala
scala> sql("create table t(a int)")
scala> sql("drop table t")
scala> sql("create table t(a int)")
scala> sql("drop table t")
2018-11-12 14:55:30 WARN  SparkCatalogEventProcessor:48 - Caught exception during parsing event
org.apache.spark.sql.catalyst.analysis.NoSuchTableException: Table or view 't' not found in database 'default';
at org.apache.spark.sql.hive.client.HiveClient$$anonfun$getTable$1.apply(HiveClient.scala:81)
...
at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.getTable(ExternalCatalogWithListener.s …
```
=> [SAC-97][SQL] SAC should not fail on repeating creation/deletion of db/tables

spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvesterSuite.scala
The patch fixes some flaky tests regarding Kafka streaming query, mostly fixing too-optimistic assumptions into realistic. There was also some misunderstanding on behavior of `AtlasEntity.equals()` and the patch fixes the related part (mostly making `Set`).
Created 10 of branches pointing same commit and trigger build in Travis.
`FIXUP-flaky-kafka-test-*`
https://travis-ci.org/HeartSaVioR/spark-atlas-connector/branches
https://travis-ci.org/hortonworks-spark/spark-atlas-connector/branches
My repo + current repo = 20 branches, only one build failed. 
```
The code passed to eventually never returned normally. Attempted 3659 times over 1.0001251280499999 minutes. Last failure message: assertion failed: Partition [sparkwrite, 0] metadata not propagated after timeout. …
```
=> [SAC-105][TEST] Fix flaky test in Kafka streaming query

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala
This aims to support `atlas.spark.column.enabled` in SQL spark_process.
=> [SAC-126][SQL] Support `atlas.spark.column.enabled` in SQL spark_process

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
This PR aims to update `SaveIntoDataSourceCommand` to handle `AnalysisBarrier` which is introduced by SPARK-24867. While upgrading to 2.3.0 to 2.3.1, we missed to test this. This is required for `atlas-1.1` branch only.
Manual. (This is tested in the Spark 2.3.2 cluster.)
This closes #147
=> [SAC-147][SQL] Update SaveIntoDataSourceCommand harvest pattern to handle `AnalysisBarrier`

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
This PR removes unnecessary classpath checks for HWC support in SAC.
Manually tested. It works with/without HWC jar correctly.
With:
Without:
Closes #160
=> [SAC-160] Remove unnecessary classpath checks for HWC support

pom.xml
This PR aims to update Kafka dependency from 2.0.0 to 2.0.1.
This closes #198
=> [SAC-198][BUILD] Update Kafka to 2.0.1

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForHiveMetastoreTableSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala
This patch proposes adding harvester to handle `CreateTableCommand` which is used to create Hive table.
Newly added UT.
This closes #225
=> [SAC-225][SQL] Add harvester to handle CreateTableCommand

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/ml/MLPipelineEventProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateViewHarvesterSuite.scala
This patch addresses missing spot while applying ProcessEntityValidator, as well as cleans some unused code/imports.
Existing UTs.
=> [MINOR][CORE] Apply ProcessEntityValidator to missing spot, code clean

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasStreamingQueryEventTracker.scala
Please refer #252 to see the rationalization of this patch.
This patch fixes the intermittent NPE occurred in SAC side when executing Streaming query, which is occurred due to receiving streaming event before executing actual batch. This can be easily reproduced via executing streaming query and let query consuming all the available input data, and stop the query, and restart the query in new spark session (spark-shell) which leverage same checkpoint.
This patch checks whether the last executed physical plan is available, and skips processing it if the plan is not available. This effectively makes SAC to wait until the plan is available (since streaming event will be sent at least per each batch, so eventually it will be available).
Manually tested: patched SAC didn't throw NPE with no …
=> [SAC-252][CORE] Skip evaluating streaming event when query is not physically executed yet

spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForComplicatedQuerySuite.scala
This patch adds a new kind of UT - complicated query which would be like chained queries.
Newly added UT.
=> [MINOR][SQL] Add UT for complicated query like chained queries

spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/ExtractFromDataSource.scala
Please refer #266 to see rationalization on this.
This patch proposes updating logic for Kafka reflection to make it become compatible with both Spark 2.4 and Spark 2.4 + SPARK-25501 applied.
Manually tested with both Spark 2.4.0 / Spark 2.4.0 with SPARK-25501 applied.
1) Spark 2.4.0
> query
```
val bootstrapServers = "localhost:9027"
val checkpointLocation = "/tmp/mykafkaaaa"
val sourceTopics = Seq("sparksource1streaming", "sparksource2streaming").mkString(",")
val sourceTopics2 = Seq("sparksource2streaming", "sparksource3streaming").mkString(",")
val targetTopic = "sparksinkstreaming"
val df = spark.readStream.format("kafka").option("kafka.bootstrap.servers", bootstrapServers).option("subscribe", sourceTopics).option("startingOffsets", "earliest").option("kafka.atlas.cluster.name", …
```
=> [SAC-266][SQL] Update Kafka reflection logic to reflect change on SPARK-25501

README.md
This patch adds explanation on "known limitations" (based on decision decision or other technical reason), as well as recent change on Spark models vs Hive models which is pretty hard to understand unless end users track the code changes.
N/A
This closes #223
=> [SAC-223][DOC] Document "known limitations", and recent change on Spark models vs Hive models
