spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateViewHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHarvesterSuite.scala
Changes:
Merge code supporting "Insert Into" and "Create View xx As Select * From xx" into master branch. 
Testing:
New unit tests were added.
I manually tested this PR in HDP cluster:
Case1:
sql("create table table_parquet_200 (a int) using parquet")
sql("insert into  table table_parquet_200 values (200)")
sql("create table table_parquet_300 (a int) using parquet")
sql("INSERT INTO table_parquet_300  SELECT * FROM table_parquet_200")
Case2:
sql("CREATE TABLE t00000(a int)")
sql("INSERT INTO t00000 VALUES (1)")
sql("CREATE TABLE t10000(a int)")
sql("INSERT INTO t10000 SELECT * FROM t00000")
Case 3: 
sql("CREATE TABLE sourceTable(a int)")
sql("INSERT INTO sourceTable VALUES (1)")
sql("CREATE view s_view1 as select * from sourceTable")
=> Add supports to Insert Into

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateHiveTableAsSelectHarvesterSuite.scala
Change:
CreateHiveTableAsSelectHarvesterSuite failed because of some changes happened in Spark 2.3.1 branch.
Testing:
Pass the current unit tests.
=> Fix CreateHiveTableAsSelectHarvesterSuite failure

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExtension.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala
Changes:
Add class SparkExtension.
How to use:
Add "--conf spark.sql.extensions=com.hortonworks.spark.atlas.sql.SparkExtension" in the command line.
Testing:
Manually tested in HDP cluster:
=> Make user SQL queries shown on process entities

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHarvesterSuite.scala
Changes:
Added supports for multiple source tables and destination tables ( `InsertInto` queries). 
Tests:
New unit tests were added.
Manually tested in HDP cluster.
Case1: multiple source tables
```
sql(s"CREATE TABLE inputTable1 (a int, b string)")
sql(s"INSERT INTO inputTable1 VALUES(1, 'str1')")
sql(s"CREATE TABLE inputTable2 (c int, d string)")
sql(s"INSERT INTO inputTable2 VALUES(1, 'str2')")
sql(s"CREATE TABLE inputTable3 (e int, f string)")
sql(s"INSERT INTO inputTable3 VALUES(1, 'str3')")
sql(s"CREATE TABLE outputTable1 (a int, b string, c int, d string, e int, f string)")
sql("INSERT INTO outputTable1 " +
"SELECT * FROM inputTable1, inputTable2, inputTable3 " +
"where inputTable1.a = inputTable2.c AND inputTable1.a = inputTable3.e")
```
Case2: multiple destination tables
``` …
```
=> InsertInto: support multiple source tables and destination tables

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
Changes: 
Support hdfs data source.
Tests:
Manually tested in HDFS cluster.
Case1:
```
spark.read.orc("/tmp/users.orc").write.save("/tmp/users0.orc")
```
Case2:
```
spark.read.json("/tmp/people.json").write.save("/tmp/people0.json")
```
=> [SAC-13] Support hdfs data source

pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala
Changes:
1. If users wants to use this feature, their spark needs to backport this PR: https://github.com/hortonworks/spark2/pull/5
2. Add KafkaHarveste to create kafka_topic entities.
Testing:
In spark-shell:
```
// read from 3 topics: 'spark2', 'spark3', and 'sparkmore'
val df = spark.readStream.format("kafka").option("kafka.bootstrap.servers", "localhost:9092").option("subscribe", "spark2,spark3,sparkmore").option("startingOffsets", "earliest").load()
//write into the topic 'spark6':
df.writeStream.format("kafka").option("kafka.bootstrap.servers", "localhost:9092").option("checkpointLocation", "/tmp/mykafka").option("topic", "spark6").start()
```
Result in Atlas:
=> [SAC-13] Support KafKa data source

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
This PR is to fix a bug of supporting multiple input hdfs files. 
Testing:
In spark-shell:
```
case 1:
val df = spark.read.load("/tmp/parfile/users.parquet")
df.write.mode("overwrite").save("/tmp/outfile1.parquet")
case 2:
val df = spark.read.load("/tmp/parfile/allFilesAreParquet/")
df.write.mode("overwrite").save("/tmp/outfile2.parquet")
case 3:
val df = spark.read.load("/tmp/parfile/*.parquet")
df.write.mode("overwrite").save("/tmp/outfile3.parquet")
```
Results without this PR:
For these three cases, their lineages shown in Atlas have only one input entity (just like the picture for case 1 below).
Results with this PR in Atlas:
Case 1:
Case 2:
Case 3:
=> [SAC-27]Fix Issues of Support Multiple Input Files (InsertInto)

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala
Changes:
1. Fix a bug about the parameters' positions of `getTableQualifiedName(cluster, nameSpace, tableName)` function.
2. Fix a bug about missing passing SQL query as parameter when creating spark_process entity for some harvesters, e.g. `InsertIntoHiveTableHarvester` and `InsertIntoHadoopFsRelationHarvester`.
3. Support more SHC cases. Before this PR, SAC creates spark_process only when HBase table is the input. Now, with this PR, it can create spark_processes which use HBase entity as both the input and the output.
Testing:
Manually tested in HDP cluster:
HBase tables: t_demo_in200 (as input), t_demo_o200(as output)
Hive table: demo_table_shc200 (as output)(df.write.format("hive").mode(SaveMode.Append).saveAsTable("demo_table_shc200"))
Case 1: Hbase table "t_demo_in200" is the input, …
=> [SAC-33] Support HBase entities both as an input and an output

.travis.yml, pom.xml, scalastyle-config.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExtension.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala
This PR enables scala style check in Travis.CI.
Pass Travis CI.
This closes #21 .
=> [SAC-21] Add a scala style and fix style errors

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanTracker.scala
Changes:
`SparkExecutionPlanTracker` and `CommandsHarvester` are in different threads, so we need to save users' SQL queries into `QueryDetail` included in query events, then `CommandsHarvester` can get the sql queries from query events.
Testing:
Manually tested in HDP cluster. Without this PR, the sql queries can not show in Atlas UI. With this PR, the sql queries can not show in Atlas UI:
This closes #38  .
=> [SAC-38] Fix issues to support sql queries shown in Atlas UI

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala
This PR update the name of Atlas record for Spark Process with Application ID. 
Attached the output figure later.
=> [SAC-55] Update the Spark Process Atlas record name

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasStreamingQueryEventTracker.scala
For a Spark Streaming query, we track the related event but we do not need to update the process entity for each patch. 
Manually test
=> [SAC-57] Reducing overhead to update entity for Spark Streaming query processing #57

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkStreamingQueryEventProcessor.scala
When Spark streaming querying sink the data into console, the console output is not a Atlas entity. Thus, we do not track this. 
Manually test
=> [SAC-59] Spark streaming query sink to console is not atlas entity #59

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/ml/MLPipelineEventProcessor.scala
Spark ML job need to store the pipeline and model into HDFS, we update the related directory into the same file entity as SQL processing related entity. 
Manually test
=> [SAC-61] Update the Spark ML model and pipeline related directory entity #61

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CatalogEventToAtlasIT.scala
Record the create information for the Hive and Spark DB entity. 
Local test and test on a real cluster.
=> [SAC-68] Fix the issue of Owner details are missing in DB entity

pom.xml
Exclude Guava from Uber jar, since Altas 1.0 are using Guava 19.0
Local test
=> Exclude Guava from the Atlas Client V2

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/ml/MLPipelineEventProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/ml/MLPipelineTrackerIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/ml/MLPipelineWithSaveIntoSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/MLAtlasEntityUtilsSuite.scala
We remove the unnecessary Spark ML event related information like Spark ML model and Spark ML pipeline. Thus, we need to update the SAC side. 
Local test
=> Update ML event tracker to match the update on the Spark ML side

pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala, spark-atlas-connector/src/test/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvesterSuite.scala
What is proposed in the PR
----
For now, we're extracting destination topic from KafkaStreamWriter. Unfortunately neither KafkaStreamWriter is a case class nor topic is a field, so it requires custom patch on Spark side as well, and we are also leveraging reflection to extract the value.
Hopefully KafkaStreamWriterFactory is a case class instead (Spark branch-2.4 as well as master branch), so we can leverage this to get rid of custom patch as well as reflection. The cost of createWriterFactory is tiny (case class object creation) for this case, and we can find the way to cache it once we find the cost is not ignorable.
How the patch is tested
----
Another small code block to check whether pattern matching against KafkaStreamWriterFactory works.
This closes #79
=> [SAC-79] Leverage KafkaStreamWriterFactory to avoid reflection while getting destination topic

spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvesterSuite.scala
This is a follow-up change what I found from #81: actual test on pattern matching in SparkExecutionPlanProcessor.
=> [SAC-79][FOLLOWUP] Add actual UT for streaming query with Kafka Source/Sink

pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvesterSuite.scala
* Modify the changeset of #80 to work along with Spark 2.3.x
* Also add UTs for KafkaHarvester
Please check the difference between this patch and #80 : Micro-batch source of Kafka connector relies on DSv1, while continuous source relies on DSv2. Moreover there's some difference on DSv2 (Spark 2.4 sorted out some odd things like `InternalRowXXX`.)
While I added code for continuous mode, I don't expect continuous mode to trigger listener to get executed plan (it will not be finished), so spark-atlas can't work with continuous mode.
=> [SAC-79] Leverage KafkaStreamWriterFactory to avoid reflection while getting destination topic (Spark 2.3.x)

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHarvesterSuite.scala
Hive Metastore provides multiple Catalogs. SAC assumes that it has own `spark` catalog which consists of fully accessible non-transactional tables. `spark` catalog is new one which is created by the following method.
https://cwiki.apache.org/confluence/display/Hive/Hive+Schema+Tool
```bash
$ schematool \
-dbType mysql \
-createCatalog spark \
-catalogDescription 'Default catalog, for Spark' \
-catalogLocation hdfs://cluster:8020/apps/spark/warehouse
```
UTs are modified and this is also tested with Apache Spark 2.4.0 and Atlas 1.1.0 with embedded HBase/Solr manually.
This closes #83 .
=> [SAC-83] Use Spark Catalog

build/mvn, pom.xml
This adds `build/mvn` to download Apache Maven and run. This is useful in the cluster which doesn't have maven installation.
Manual.
```
$ build/mvn clean
```
=> [SAC-85][BUILD] Add Apache Maven wrapper to download and run

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClientConf.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasEventTracker.scala
This PR supports `atlas.spark.enabled`. If `atlas.spark.enabled` is `false` in `atlas-application.properties`, Spark Atlas Connector will not populate Spark-related Atlas model and not create Spark entity create events.
The default value of `atlas.spark.enabled` is `true` because the users already register Spark Atlas Listners.
Manually tested with Apache Atlas 1.1.0 (embedded HBase/Solr).
=> [SAC-87] Support `atlas.spark.enabled` configuration

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasEventTracker.scala
Currently, SAC repeats Spark's warning on query failures. Since SAC is one of the listeners, we had better be silent.
Manual with Apache Atlas 1.1.0 (with embedded HBase/Solr) and Apache Spark 2.4.0.
This closes #89
=> [SAC-89] SAC should not warn on query failures

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/AtlasEntityReadHelper.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/AtlasQueryExecutionListener.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/CreateEntitiesTrackingAtlasClient.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/DirectProcessSparkExecutionPlanProcessor.scala
This patch fixes the bug which doesn't register entities to Atlas for below query:
```
val df = spark.read.csv("abc.csv")
df.write.saveAsTable("app_details")
``` 
After applying the patch, SAC correctly registers Atlas entities: spark_process, spark_db, spark_table, fs_path.
* Added UT
* Manually verified with Atlas 1.1 (local HBase, local Solr) & Spark 2.4
=> [SAC-94] Fix df.write.saveAsTable to be correctly logged to Atlas

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/AtlasEntityReadHelper.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/AtlasQueryExecutionListener.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/CreateEntitiesTrackingAtlasClient.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/DirectProcessSparkExecutionPlanProcessor.scala
This patch fixes the bug which doesn't register entities to Atlas for below query:
```
val df = spark.read.csv("abc.csv")
df.write.saveAsTable("app_details_spark_2_3")
``` 
After applying the patch, SAC correctly registers Atlas entities: spark_process, spark_db, spark_table, fs_path.
* Added UT
* Manually verified with Atlas 1.1 (local HBase, local Solr) & Spark 2.3
=> [SAC-94] Fix df.write.saveAsTable to be correctly logged to Atlas (atlas-1.1)

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClientConf.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessorSuite.scala
This PR aims to add `atlas.spark.column.enabled` configuration.
Pass the Travis CI with the updated test cases.
This is also tested manually with Apache Atlas 1.1.0 and Apache Spark 2.4.0.
This closes #101
=> [SAC-101][SQL] Add `atlas.spark.column.enabled` configuration

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaTopicInformation.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvesterSuite.scala
This patch introduces SAC specific parameter for Kafka source and sink: `kafka.atlas.cluster.name`. If the option is given for source / sink, SAC uses the value of configuration to atlas cluster name for Kafka topic entity.
Updated UT passed, Manually tested with Spark 2.4 & Atlas 1.1 with below structured streaming app:
```
val bootstrapServers = "localhost:9092"
val checkpointLocation = "/tmp/mykafka3"
val sourceTopics = Seq("sparksource1hdp30", "sparksource2hdp30").mkString(",")
val sourceTopics2 = Seq("sparksource2hdp30", "sparksource3hdp30").mkString(",")
val targetTopic = "sparksinkhdp30"
val df = spark.readStream.format("kafka").option("kafka.bootstrap.servers", bootstrapServers).option("subscribe", sourceTopics).option("startingOffsets", …
```
=> [SAC-103] Support custom atlas cluster name for Kafka topics (source/sink)

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClientConf.scala
This configuration is tested on the cluster for both values. This PR aims to change the default value to `false`.
This closes #106
=> [SAC-106][SQL] Disable `atlas.spark.column.enabled` by default

spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvesterSuite.scala
We already have `CLUSTER_NAME` in `AtlasClientConf`. This PR removes the duplicated new configuration `KafkaHarvester.CONFIG_CUSTOM_CLUSTER_NAME` and use the existing one instead. This will reduce future confusion.
This closes #108
=> [SAC-108][KAFKA] Remove KafkaHarvester.CONFIG_CUSTOM_CLUSTER_NAME

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessorSuite.scala
To be consistent with Hive, we had better create it in lower cases.
Manual. This should be tested widh 
```
val ATLAS_SPARK_COLUMN_ENABLED = ConfigEntry("atlas.spark.column.enabled", "false")
```
This closes #110
=> [SAC-110][SQL] Spark's Hive catalog column name should be lower cases

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/ml/MLPipelineTrackerIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/MLAtlasEntityUtilsSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasEntityUtilsSuite.scala
This adds `clusterName` field to Spark's Hive Table model (`metadata.DB_TYPE`) additionally. This information was already shown in `qualifiedName` field, too.
Pass the Travis CI with the updated test case.
Also, this is verified with Apache Atlas 1.1.0 and Apache Spark 2.4.0.
This closes #112 .
=> [SAC-112][SQL] Add `clusterName` to Spark Database entity

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasEntityUtilsSuite.scala
This PR renames attribute `database` to `db` in Spark table model. This is the consistent name with Hive and work like the following.
Pass the Travis CI with the updated test case.
Also, this is verified manually with Apache Spark 1.1.0 and Apache Spark 2.4.0.
This closes #114 .
=> [SAC-114][SQL] Rename attribute `database` to `db` in Spark table model

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/TestUtils.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CatalogEventToAtlasIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasEntityUtilsSuite.scala
This PR adds 'ownerType' attribute to Spark Table entity.
Pass the Travis CI with the updated test case.
This is also tested with Apache Atlas 1.1.0 and Apache Spark 2.4.0.
This closes #116 .
=> [SAC-116][SQL] Add 'ownerType' to Spark Table entity

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
This PR add a logic to handle `OneRowRelation`.
```scala
scala> sql("create table ctas1 as select 1 a")
... WARN  CommandsHarvester$:44 - Missing unknown leaf node: OneRowRelation
```
This should be tested manually since this removes only WARN message.
This closes #118
=> [SAC-118][SQL] CTAS should not warn `Missing unknown leaf node`

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/KafkaAtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/RestAtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/HWCStreamingHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessorSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/CreateEntitiesTrackingAtlasClient.scala
This PR proposes to add HWC support in SAC.
Hive Warehouse Connector currently supports four types of operations:
1. SQL / DataFrame Read (batch read)
2. SQL / DataFrame Write (batch write)
3. SQL / DataFrame Write in streaming manner (batch write in streaming)
4. Structured Streaming Write (streaming write)
For 1., it is supported by looking logical plans (if available) or physical
plans up at `HWCEntities` for every execution plan being processed above
when it's possible.
For 2. and 3., it checks only when the execution plan is `WriteToDataSourceV2Exec`.
It checks the write implementation of DataSourceV2 is HWC or not and dispatches to harvest
appropriate entities.
For 4., it is same as 2. and 3. but it reuses Kafka harvester to handle input sources
under the hood when it dispatches to …
=> [SAC-124][SQL] Hive Warehouse Connector support

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHarvesterSuite.scala
Atlas doesn't support cycle. Currently, Spark fails like the following. Hive omits the out-going edge to avoid this situation.
```scala
scala> sql("insert into t select * from t")
18/11/20 19:18:24 WARN RestAtlasClient: Failed to create entities
java.lang.IllegalStateException: Fail to get create entities
at com.hortonworks.spark.atlas.RestAtlasClient.doCreateEntities(RestAtlasClient.scala:73)
```
**AFTER**
- Pass the Travis CI with newly added test cases.
- Also, this is verified with Apache Atlas 1.1.0 and Apache Spark 2.4.0.
=> [SAC-128][SQL] Cyclic `INSERT INTO` should not generate outbound link

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateViewHarvesterSuite.scala
This PR aims to handle `OneRowRelation` and remove nested column information.
```scala
scala> sql("create view v1 as select 1")
WARN SparkExecutionPlanProcessor: Caught exception during parsing event
java.lang.ClassCastException: org.apache.spark.sql.catalyst.plans.logical.OneRowRelation cannot be cast to org.apache.spark.sql.catalyst.analysis.UnresolvedRelation
```
=> [SAC-133][SQL] CREATE VIEW should support OneRowRelation

README.md, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClientConf.scala
This patch changes the default client to Kafka which provides better stability and security. Rest API client is still supported via setting `atlas.client.type` to `rest`.
Manually tested (Spark 2.4, Atlas 1.1 with embedded HBase, Solr, Kafka)
This closes #135
=> [SAC-135] Change default client to Kafka

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/KafkaAtlasClient.scala
This patch changes Kafka Client (AtlasHook) to use API V2 which is already used in REST Client. This avoids possibility on errors while converting V1 to V2 in Atlas side.
Please refer #137 for more details.
Manual tests: verified against below scenarios with Spark 2.4/Atlas 1.1
1. Create/Alter/Delete table
```
spark.sql("create table test_spark_kafka_4 (col1 int)")
spark.sql("alter table test_spark_kafka_4 add columns (col2 int)")
spark.sql("drop table test_spark_kafka_4")
```
Table entity and relevant entities are created when executing `create table`, and table entity got removed when executing `drop table`.
"atlas.spark.column.enabled" is set to "true" when testing above queries. Column reference error occurred when updating spark_table which is expected, but col2 is added properly.
2. …
=> [SAC-137] Use API V2 for Kafka Client (AtlasHook)

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
This PR proposes to make HWC's SQL syntax recognisable. Currently SAC and HWC only know the query that has to be pushed down to Hive side so here we don't know which tables are to be proceeded. To work around, we use Spark's parser driver to identify tables. Once we know the table identifiers by this, it looks up Hive entities to find Hive tables out.
Manually tested via a Yarn secure cluster.
Closes #141
=> [SAC-141] Make SAC recognise HWC's SQL API

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessorSuite.scala
This addresses missing spot on handling "atlas.spark.column.enabled" for the event `AlterTable`.
Modified UT. Also done with manual test against below queries:
```
spark.sql("create table test_spark_kafka_b3 (col1 int)")
spark.sql("alter table test_spark_kafka_b3 add columns (col2 int)")
spark.sql("drop table test_spark_kafka_b3")
```
Before applying the patch, alter table query threw error on Atlas side, whereas this patch properly skips handling columns.
This closes #139
=> [SAC-139] Apply "atlas.spark.column.enabled" for event AlterTable

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClient.scala
This PR make AtlasClient thread-safe to avoid duplicated entity creation. Currently, it is possible that the client makes duplicated entities since SAC has multiple threads that uses Atlas clients.
For instance, as below:
Manually tested:
It's a bit tricky to add a test.
Closes #143
=> [SAC-143] Make AtlasClient thread-safe to avoid duplicated entity creation

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/utils/SparkUtils.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateDataSourceTableAsSelectHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala
This PR proposes to refer catalog before creating spark_table entities when possible. Looks there could be `CatalogTable` being passed as kind of a dummy in some places in Spark.
For instance, see the test added that mimics `DataFrameWriter.saveAsTable` code path. It causes missing table information as below:
Unit test added to describe what happens and prevent regression. Manually tested as well:
Closes #144
=> [SAC-144] Refers catalog before creating spark_table entities when possible

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala
This patch proposes dropping attribute 'lastAccessTime' in table entity due to difficulty of updating such attribute.
Please refer #150 for more details on the decision.
Manually tested with Atlas 1.1 (embedded HBase/Solr/Kafka) & Spark 2.4.
This closes #150.
=> [SAC-150][SQL] Drop attribute 'lastAccessTime' in table

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
This PR aims to support multi HBase cluster use cases by accepting `atlas.cluster.name` from users. The basic usage is the same with Kafka.
```scala
df.write
.format("org.apache.spark.sql.execution.datasources.hbase")
.option("catalog", cat)
.option("atlas.cluster.name", "customClusterName")
.save()
```
Manual. (This is tested manually with Apache Spark 2.4/Apache Atlas 1.1 with embedded HBase.)
This closes #152 .
=> [SAC-152][SQL] Support `atlas.cluster.name` option for HBase entity

patch/Spark_Kafka_Custom_Atlas_Cluster_Name_2.3.diff, patch/Spark_Kafka_Custom_Atlas_Cluster_Name_2.3.patch, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvester.scala, spark-atlas-connector/src/main/scala/org/apache/spark/sql/kafka010/atlas/KafkaTopicInformation.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/org/apache/spark/sql/kafka010/atlas/KafkaHarvesterSuite.scala
This patch proposes applying #103 against Spark 2.3 as well. Previously we dropped applying Spark 2.3 because it requires custom patch for Spark 2.3, and now we just decided to proceed with custom patch. 
This patch leverages reflection to access newly exposed field. If Spark is not patched, SAC will print out WARN message and will not extract custom atlas cluster name.
Manually tested against Atlas 1.1 & Spark 2.3.2 & patched spark-sql-kafka 2.3.2.
```
val sourceTopics = Seq("sparksource1-20181213", "sparksource2-20181213", "sparksource3-20181213").mkString(",")
val targetTopic = "sparksink-20181213"
val df = spark.readStream.format("kafka").option("kafka.bootstrap.servers", bootstrapServers)
.option("subscribe", sourceTopics).option("startingOffsets", "earliest") …
```
=> [SAC-156] Spark 2.3 - Support custom atlas cluster name for Kafka topics (source/sink)

spark-atlas-connector-assembly/pom.xml
This PR shades Atlas's HBase/HTrace dependencies to avoid conflicts with Spark HBase Connectors.
Pass the build and tests in Travis. (Also, this is tested in the cluster).
=> [SAC-163][BUILD] Shade Atlas's hbase/htrace dependencies

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasEntityUtilsSuite.scala
This patch fixes the reference of old attribute name `storage` to new name `sd`. Also fixed relevant UT as well.
Existing UT, as well as modified UT.
=> [SAC-170] Fix the old attribute name in spark table entity (storage -> sd)

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClient.scala
I made a mistake at
https://github.com/hortonworks/spark-atlas-connector/commit/ee104f4c7f8773eba4519f7522d65d12048e0af7
This PR makes the client still thread-safe.
Manually tested
=> [SAC-124][SQL][FOLLOW-UP] Make AtlasClient's createEntities thread-safe

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala
This patch fixes the missing spot which `spark_schema` attribute is not dropped in spark table entity whereas column entities are dropped correctly, which raises error on Atlas side.
Manually tested against Spark 2.4 & Atlas 1.1. (This bug is not triggered without #172 though.)
This closes #174
=> [SAC-174] Drop `spark_schema` attribute correctly when column is disabled

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala
Followup of https://github.com/hortonworks-spark/spark-atlas-connector/pull/177. When HWC is output, it is also possible for SHC to be its input.
Manual
=> [SAC-176][SQL][FOLLOW-UP] Harvest SHCEntities when HWC is output as well

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/BaseResourceIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/KafkaTopicEntityValidator.scala
This patch addresses the bug which Kafka topic is not recorded when saving DF to Kafka via DF.save().
This patch also refactors the code regarding testing Kafka entity a bit to reduce redundant lines.
Added UT. Also manually tested with Spark 2.4 & Atlas 1.1.
```
// prepare
spark.sql("create table default.s4_spark_t1_1658400062_a (col1 int)")
spark.sql("insert into s4_spark_t1_1658400062_a values(1)")
// test query
spark.sql("select * from s4_spark_t1_1658400062_a").selectExpr("cast(col1 as String) value").write.format("kafka").option("kafka.bootstrap.servers", "localhost:9027").option("topic", "test_spark_topic_WIP_BUG_116565").option("kafka.atlas.cluster.name", "custom_cluster").save()
```
This closes #184
=> [SAC-184][SQL] Record Kafka topic entity correctly when saving DF to Kafka via DF.save()

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasStreamingQueryEventTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/streaming/HWCStreamingHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/streaming/KafkaHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/streaming/SparkStreamingQueryEventProcessor.scala
This PR proposes to record Structured Streaming HDFS <> HWC.
```scala
import org.apache.spark.sql._
import com.hortonworks.spark.sql.hive.llap.HiveWarehouseBuilder
val hive = HiveWarehouseBuilder.session(spark).build()
import org.apache.spark.sql.types._
val schema = StructType(
Array(
StructField("col0", StringType),
StructField("col1", StringType)))
spark.readStream.schema(schema).json("/tmp/hyukjinkwon_json_data")
.writeStream
.format("com.hortonworks.spark.sql.hive.llap.streaming.HiveStreamingDataSource")
.option("table", "s12_hive_1_562160834")
.option("checkpointLocation", "/tmp/s12_hive_1_562160834/check")
.option("metastoreUri", "thrift://ctr-e139-1542663976389-39519-01-000003.hwx.site:9083,thrift://ctr-e139-1542663976389-39519-01-000005.hwx.site:9083")
.start()
```
The problem …
=>  [SAC-193][SQL] Support to record Structured Streaming (HDFS <> HWC)

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/KafkaAtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/RestAtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessorSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/CreateEntitiesTrackingAtlasClient.scala
Currently, HWC entities are not created if Kafka client is used. This PR proposes to add the support for HWC with Kafka client.
For instance, the codes below does not create the lineage for HWC operations.
```scala
sql("create table test using parquet location '/tmp/hyukjin_parquet'")
import com.hortonworks.spark.sql.hive.llap.HiveWarehouseBuilder
val hive = HiveWarehouseBuilder.session(spark).build()
spark.sql("select * from test").write.mode("append").format("com.hortonworks.spark.sql.hive.llap.HiveWarehouseConnector").option("table", "hive_t2_hyukjin").save()
```
Previous way used `findEntity` which only exists in REST client. The problem was nested entity reference problem. For instance, table entity needs storage description entity but when we harvest we don't have full information …
=> [SAC-201][SQL] Add support for Kafka client for HWC

spark-atlas-connector-assembly/pom.xml
This PR shades and relocates Atlas's commons-configuration dependency to avoid conflicts when running SparkAtlasModel (to create models before running SAC). This is needed to enable #166.
Passed UTs, tested with Spark 2.4 & Atlas 1.1 (master branch), Spark 2.3.2 & Atlas 1.1 (atlas-1.1 branch)
=> [SAC-208][BUILD] shade & relocate commons-configuration

README.md
This patch proposes documenting how to pre-create Atlas models, so that end users can run it only once and disable the option to check and create models at every startup of SAC.
Manually tested: executing command against fresh Atlas cluster, and check whether spark models are available.
=> [SAC-165][Documentation] Document how to pre-create Atlas models

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/SparkAtlasModel.scala
This patch provides the option to get auth information interactively on SparkAtlasModel CLI, which gets rid of necessary to store auth information as plain text in properties file.
Manually tested with additional log messages when verifying. Now the log message which shows username only left.
This closes #212
=> ISSUE-212 Support interactive authentication in pre-creating models

README.md
This patch adds explanation on `--interactive-auth` parameter on SparkAtlasModel which is strongly encouraged to use. Actually this should be included in #212 but missed that.
No test needed, just a doc change.
=> MINOR Add explanation on interactive-auth parameter of pre-creating models

pom.xml, spark-atlas-connector-assembly/pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala
This patch shades and relocates jersey 1.x (and old jackson which is compatible with) to avoid conflict with jersey 2.x in Spark UI. 
This patch also shades and relocates jackson 2.9.6 which Atlas client is pulling, since Spark 2.4.0 leverages lower version of jackson which is not compatible at some point.
This patch also removes hbase-bridge from dependency, since it pulls plenty of dependencies while it can be just replaced via copying some codes (less than 10 lines).
Existing UT passed, manually tested via following steps:
1) manual model creation succeeded
> java -cp "/atlas-dist/sac-archives/spark-atlas-connector-assembly-0.1.0-SNAPSHOT-SAC-215.jar:/spark-dist/releases/spark-2.4.0-bin-hadoop2.7/jars/*:/spark-dist/releases/spark-2.4.0-bin-hadoop2.7/conf" …
=> [SAC-215][BUILD] Shade & relocate jersey 1.x / jackson, remove hbase-bridge

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/streaming/SparkStreamingQueryEventProcessor.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/AtlasStreamingQueryProgressListener.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/DirectProcessSparkStreamingQueryEventProcessor.scala
This patch fixes the issue when streamingQueryListeners is referred as `SparkAtlasStreamingQueryEventTracker` and the streaming query doesn't use file streaming source/sink. I've described what is happening in #219 so skip describing here.
* Changed UT to check both paths (`SparkExecutionPlanProcessor`, `SparkStreamingQueryEventProcessor`) when running streaming query tests. 
* Also added UT to test file to file streaming query.
* Manually tested the same.
This closes #219
=> [SAC-219][SQL] Fix issue on non-file stream source/sink query when streamingQueryListeners is specified

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasEntityUtilsSuite.scala
This patch proposes two major changes:
1. changes Spark catalog model definitions to accommodate existing Hive catalog model definitions
2. apply the changes into both Spark catalog entities and Hive metastore based catalog entities
Below is the excel sheet which compares existing Spark catalog model definitions and Hive catalog model definitions in Atlas's master branch. 
[SAC-168-table-models-description copy.xlsx](https://github.com/hortonworks-spark/spark-atlas-connector/files/3141841/SAC-168-table-models-description.copy.xlsx)
* Modified UTs.
* Manually tested against Spark 2.4 & Atlas 1.1
The differences are shown with CTAS query:
```
spark.range(10).write.json("/tmp/sac/json-sac-168-v2")
spark.sql("CREATE TABLE test_table_sac_168_v2_a USING json location …
```
=> [SAC-168][SQL] Apply Spark catalog model definitions to Hive metastore catalog entities

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala, spark-atlas-connector/src/test/resources/atlas-application.properties, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/BaseResourceIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/KafkaClientIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CatalogEventToAtlasIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessorSuite.scala
Please refer #229 to see the details of limitation which leads to discard existing feature.
This patch proposes to discard support dropping table, as the behavior cannot be consistent, and current approach is even error-prone.
Modified UTs and ITs. ITs ran with fresh Atlas 1.1.
This closes #229
=> [SAC-229][SQL] Discard support of dropping table

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClient.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasEntityReadHelper.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasEntityWithDependencies.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/ml/MLPipelineEventProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkCatalogEventProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/TestUtils.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/ml/MLPipelineTrackerIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/ml/MLPipelineWithSaveIntoSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateDataSourceTableAsSelectHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateHiveTableAsSelectHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateViewHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHiveDirHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoRdbmsHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/LoadDataHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForHiveMetastoreTableSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForViewSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/FsEntityValidator.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/KafkaTopicEntityValidator.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/ProcessEntityValidator.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/AtlasExternalEntityUtilsSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/MLAtlasEntityUtilsSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasEntityUtilsSuite.scala
Please refer #231 to see rationalization of the patch.
This patch proposes breaking down single "create entities" request into dependency first multiple requests. To achieve this, this patch changes the basic approach of collecting entities to create, from flattened `Seq[AtlasEntity]` to `Seq[AtlasEntityWithDependencies]` which `AtlasEntityWithDependencies` has origin entity and dependencies - like a tree structure.
This patch also changes the type for reference attribute from `AtlasEntity` to `AtlasObjectId`, as Atlas cannot handle it across multiple requests. It worked when entities are included in same request.
Given this patch changes the basic approach across all codebase, this patch touches almost every parts of codebase - so instead of reviewing code changes in depth, any reviewer …
=> [SAC-231][CORE] Break down single "create entities" request into dependency first multiple requests

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasEntityReadHelper.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/SparkAtlasModel.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/BaseResourceIT.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoRdbmsHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForHiveMetastoreTableSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/AtlasExternalEntityUtilsSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/MLAtlasEntityUtilsSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasEntityUtilsSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/SparkAtlasModelIT.scala
This patch proposes change the way of linking related entities from "reference" to "relationship". This patch includes the change of models to apply relationship, as well as code change to link via relationship attribute instead of normal attribute.
Please note that this patch don't change the current approach for "process" and "aws s3" types, since these models define these attributes in both attributes and relationship attributes.
Modified UTs, ITs with fresh Atlas 1.1, manually tested with Spark 2.4 & Atlas 1.1 via below query:
> query
```
val sourceTopics = Seq("sparksource1batch-sac-233", "sparksource2batch-sac-233")
val sourceTopics2 = Seq("sparksource2batch-sac-233", "sparksource3batch-sac-233")
val customClusterName = "custom_cluster"
val df = spark.read.format("kafka") …
```
=> [SAC-233][CORE] Change the approach of linking entities from "reference" to "relationship"

.travis.yml
This patch removes unnecessary running tests in Travis CI. By default, Travis CI runs `mvn test -B` after executing commands in `install` section.
Verified PR build for Travis CI. See the difference of build time between recent PR build and previous builds.
=> [MINOR][BUILD] Remove unnecessary running tests in Travis CI

README.md, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasClientConf.scala
This patch proposes disabling `atlas.client.checkModelInStart` by default to prevent REST API to be initialized with default setting. Please refer #237 for more details on rationalization.
Existing UTs and ITs.
=> [SAC-237][CORE] Disable `atlas.client.checkModelInStart` by default

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateDataSourceTableAsSelectHarvesterSuite.scala
This patch proposes to add additional attributes to spark_table viz. schema, provider, partitionProvider, partitionColumnNames.
* Modified existing UT to validate generated Atlas entity attribute.
* Manually tested.
Queries:
spark.range(10).write.json("/tmp/sac/json-wip-entity-deps")
1. spark.sql("CREATE TABLE test_table_wip_entity_deps_a USING json location '/tmp/sac/json-wip-entity-deps'")
2. spark.sql("CREATE TABLE test_table_managed_wip_entity_deps_a SELECT * FROM test_table_wip_entity_deps_a")
=> [SAC-240] [CORE] Add additional attributes to spark_table

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/utils/SparkUtils.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/LoadDataHarvesterSuite.scala
This patch proposes to use current DB name in current Spark session instead of `default` when Spark table information doesn't contain database name.
Modified UT. Without the change, `prepareEntity` fails to find table entity from "default" database.
Closes #246
=> [SAC-246][CORE] Use current db name in current Spark session when Spark table information doesn't provide db name

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasEventTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasStreamingQueryEventTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/CommandsHarvester.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/AtlasEntityUtils.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/metadata.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/ml/MLPipelineWithSaveIntoSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateDataSourceTableAsSelectHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateHiveTableAsSelectHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/CreateViewHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/InsertIntoHiveDirHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/LoadDataHarvesterSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForBatchQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/AtlasQueryExecutionListener.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/AtlasStreamingQueryProgressListener.scala
This patch proposes dropping `executionTime` attribute as `executionTime` attribute actually simply doesn't make sense for `spark_process` - `spark_process` is assigned per application, whereas Spark provides the value per query.
UTs. The code change is obvious so didn't do manual tests.
This closes #248
=> [SAC-248][CORE] Drop attribute `executionTime` in `spark_process`

pom.xml
This patch proposes to exclude Hadoop dependencies from Beeju and leverages Hadoop dependencies from Spark. (Beeju is in "test" scope, which won't make problem in usage.)
The base ground of this decision is, if Hadoop version conflict occurs between Beeju and Spark, we should rely on Spark which cannot be replaceable.
Existing UTs.
Closes #256
=> [SAC-256][BUILD] Exclude Hadoop dependencies from Beeju

spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/AtlasEntityCreationRequestHelper.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/SparkAtlasStreamingQueryEventTracker.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessor.scala, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/internal.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/AtlasEntityCreationRequestHelperSuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/SparkExecutionPlanProcessorForStreamingQuerySuite.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/sql/testhelper/KafkaTopicEntityValidator.scala
Please refer #253 to see rationalization of this patch.
This patch proposes to evaluate all streaming events from streaming listener to capture late activated sources and sinks in streaming query. This change will incur huge requests to Atlas (at least one per batch), so this patch also introduces some optimization on sending request to Atlas.
The approach of optimization is memorizing accumulated inputs and outputs per streaming query and only sending request when either new inputs or new outputs is not a subset of accumulated inputs or outputs.
Added UTs
* UTs for class doing optimization
* another UT for simulating late source activation on streaming query
(skipping manual tests since one of new UT plays like acceptance test.)
This closes #253
=> [SAC-253][SQL] Streaming query should evaluate all events from streaming listener, but should update efficiently

pom.xml, spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/types/external.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/WithHDFSSupport.scala, spark-atlas-connector/src/test/scala/com/hortonworks/spark/atlas/types/AtlasExternalEntityUtilsSuite.scala
Please refer #263 for more details.
This patch proposes path to be qualified with Spark default filesystem when scheme of the path is not specified.
Added UT. Also manually tested.
> query
```
import org.apache.spark.sql.types.StructType
val userSchema = new StructType().add("col0", "string").add("col1", "string").add("col2","string")
val df = spark.readStream.schema(userSchema).json("/tmp/stream_messages")
df.writeStream.format("json").option("checkpointLocation","/tmp/chkpt").option("path","/tmp/hdfs_streams").start()
```
> screenshots
Without this patch, these entities are created as `fs_path`.
This closes #263
=> [SAC-263][CORE] Qualify path with Spark default filesystem when scheme is not specified

pom.xml
This patch proposes upgrading Atlas version to 2.0.0 which is new major version of Atlas.
This patch also excludes unnecessary dependencies which unintentionally pull commons-configuration 1.6 - maven somewhat works unwanted and assembly jar unintentionally contains commons-configuration 1.6. This patch fixes the case.
Existing UTs, manually tested with Apache Spark 2.4.3 & Apache Atlas 2.0. Model initialized with official spark model in Atlas (not included in any official release yet)
https://github.com/apache/atlas/blob/master/addons/models/1000-Hadoop/1100-spark_model.json
> query
```
val sourceTopics = Seq("sparksource1batch", "sparksource2batch")
val sourceTopics2 = Seq("sparksource2batch", "sparksource3batch")
val customClusterName = "custom_cluster"
val df = …
```
=> [SAC-269][CORE] Upgrade Atlas version to 2.0.0
